
project_id = "dmgrgzysrzzgsajwqyrh"

[[functions]]
name = "scrape-images"
verify_jwt = true

[[functions]]
name = "analyze-image"
verify_jwt = false

[[functions]]
name = "generate-avatar"
verify_jwt = false
