project_id = "dmgrgzysrzzgsajwqyrh"

[functions.analyze-item-image]
verify_jwt = false

[functions.generate-background]
verify_jwt = false

[functions.generate-3d-model]
verify_jwt = false

[functions.search-item-prices]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false

[functions.add-item-chat]
verify_jwt = false
